id: 3ce480000eb14c9ab3a5634fb23ad17f
initial_creation_type: ocr
source_metadata:
  volumes:
    5b9f47d607244dc59dda6d5b8f977640:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: ''
      total_pages: 1634
      volume_number: 18
