id: D55666276
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:15:58+00:00'
last_modified: '2022-05-26T10:15:06.386974+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9cd6:
      image_group_id: I1PD95863
      title: བདག་བྱིན་གྱིས་བརླབ་པའི་རིམ་པ་རྣམ་པར་དབྱེ་བ།
      total_pages: 1634
      order: 18
      base_file: 9cd6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
